# conda env create -f C:\Users\tgerrish\Documents\GitHub\climate\environment.yml python=3.5

name: tg_climate
dependencies:
  - numpy
  - pandas
  - matplotlib
  - pymongo
  - jupyter
  - nbconvert
  - astropy